FROM  harbor.pmjaydevmgmt.tatacommunications.com/abdm/openjdk:17.0-jdk
ENV TZ=Asia/Calcutta
RUN mkdir /APP
WORKDIR /APP
COPY app-service/target/app-service-1.0.0.jar  /APP/app-service.jar
EXPOSE 7102
RUN chmod -R 777 /APP
ENTRYPOINT ["java","-jar","-XX:ActiveProcessorCount=2","-Xms1500m","-Xmx2000m","-XX:+UseG1GC","-XX:+UseStringDeduplication","/APP/app-service.jar"]
