FROM  harbor.abdm.gov.in/abdm/openjdk:17.0-jdk
ENV TZ=Asia/Calcutta
RUN mkdir /APP
WORKDIR /APP
COPY db-service/target/db-service-1.0.0.jar  /APP/db-service.jar
EXPOSE 9188
RUN chmod -R 777 /APP
ENTRYPOINT ["java","-XX:ActiveProcessorCount=2","-Xms1g","-Xmx2g","-XX:+UseG1GC","-XX:+UseStringDeduplication","-jar","/APP/db-service.jar"]
