FROM  harbor.abdm.gov.in/abdm/openjdk:17.0-jdk
ENV TZ=Asia/Calcutta
RUN mkdir /APP
WORKDIR /APP
COPY db-service/target/db-service-1.0.0.jar  /APP/db-service-1.0.0.jar
EXPOSE 9188
RUN chmod -R 777 /APP
ENTRYPOINT ["java","-jar","/APP/db-service-1.0.0.jar"]
