

package in.gov.abdm.abha.enrollment.exception.aadhaar.model;

/**
 * @author suraj
 * 
 * Error codes for the application. 
 * 
 * Parent error code is in 3 digits like HIS-422
 * Aadhar error codes started from - HIS-2001
 * KYC error codes started from - HIS-3001 
 * Email Verification Link error code start from - HIS-600
 *
 */
public enum ErrorCode {

	SYSTEM_EXCEPTION("HIS-500"),
    INVALID_EMAIL_FORMAT("HIS-601"),
    EMAIL_VERIFICATION_EXCEPTION("HIS-602"),
	BUSINESS_EXCEPTION("HIS-422"),
	BAD_REQUEST("HIS-400"),
	UNAUTHORIZED("HIS-401"),
	DATABASE_EXCEPTION("HIS-503"),
	RESOURCE_NOT_FOUND("HIS-1001"),
	FIELD_REQUIRED("HIS-1002"),
    PATTREN_MISMATCHED("HIS-1003"),
    SIZE_MISMATCHED("HIS-1003"),
    INCORRECT_TYPE("HIS-1004"),
    RESOURCE_NOT_AUTHORIZED("HIS-1005"),
    INVALID_AUTHENTICATION_METHOD("HIS-1006"),
    RESOURCE_DISABLED("HIS-1007"),
    USER_NOT_FOUND("HIS-1008"),
    UIDAI_ERROR("HIS-1009"),
    PASSWORD_MISSMATCH("HIS-1010"), 
    MOBILE_NUMBER_MISSMATCH("HIS-1011"),
    UUID_MISSMATCH("HIS-1012"),
    OTP_MISSMATCH("HIS-1013"),
    ALPHABET_MISSMATCHED("HIS-1014"),
    HEALTH_ID_NOT_AVAILABLE("HIS-1016"),
    HEALTH_ID_NOT_LAUNCHED("HIS-1018"),
    HFR_UID_NOT_AVAILABLE("HIS-1019"),
    HFR_UID_ALREADY_EXIST("HIS-1020"),
    HFR_UID_PASSWORD_NOT_MATCHED("HIS-1021"),
    CAPTCHA_INVALID_EXCEPTION("HIS-1022"),
    OTP_FLOOD_EXCEPTION("HIS-1023"),
    STATE_NOT_VALID_EXCEPTION("HIS-1024"),
    DISTRICT_NOT_VALID_EXCEPTION("HIS-1025"),
    TRANSACTION_NOT_FOUND_EXCEPTION("HIS-1026"),
    HID_BENEFI_NOT_FOUND_EXCEPTION("HIS-1027"),
    AADHAR_NOT_BLANK_EXCEPTION("HIS-1028"),
    HID_ALREADY_EXIST_WITH_AADHAR("HIS-1029"),
    AADHAR_NAME_MISMACTHED_EXCEPTION("HIS-1030"),
    PASSWORD_NOT_SET_EXCEPTION ("HIS-1031"),
    INTEGRATED_PROGRAM_NOT_FOUND_EXCEPTION("HIS-1032"),
    HID_PASSWORD_NOT_MATCHED("HIS-1033"),
    DATE_MISSMATCH("HIS-1034"),
    HEALTH_ID("HIS-1035"),
    INVALID_TRANSACTION_EXCEPTION("HIS-1036"),
    EMPTY_BLANK_EXCEPTION("HIS-1037"),
    MOCKING_EXCEPTION("HIS-1038"),
    USER_BLOCK_EXCEPTION("HIS-1039"),
    IMAGE_VALIDATION_EXCEPTION("HIS-1040"),
    VERIFY_OTP_FLOOD_EXCEPTION("HIS-1041"),
    INVALID_TRANSITION_EXCEPTION("HIS-1042"),
    INCORRECT_REDICT_URL_EXCEPTION("HIS-1043"),
    ACCESS_CODE_EXCEPTION("HIS-1044"),
    MOBILE_UPDATE_FAILED_EXCEPTION("HIS-1045"),
    MOBILE_UPDATE_SAME_FAILED_EXCEPTION("HIS-1046"),
    OTP_PWD_ENC_INVALID_EXCEPTION("HIS-1047"),
    INVALID_TOKEN__EXCEPTION("HIS-1048"),
    CONSENT_EXCEPTION("HIS-1049"),
    MOBILE_NOT_VERIFYIED_EXCEPTION("HIS-1050"),
    BENIFIT_ID_NOT_FOUND_EXCEPTION("HIS-1051"),
    ACCOUNT_ACEEDED_EXCEPTION("HIS-1052"),
    RETRYABLE_EXCEPTION("HIS-1053"),
    INVALID_DOC_TYPE("HIS-1054"),
    HID_CURRENT_OLD_PWD_SAME("HIS-1055"),
    MOBILE_OTP_EXPIRE_EXCEPTION("HIS-1056"),
    ENROLLMENT_NUMBER_NOT_FOUND("HIS-1057"),
    GENDER_INVALID("HIS-1058"),
    DATA_INVALID("HIS-1059"),
    HEALTH_AREADY_AVAILABLE("HIS-1060"),
    PHR_ADDRESS_REQUIRD_EXCEPTION("HIS-1061"), 
    ENCRYPTION_MISSMATCH("HIS-1062"),
    PHR_DOMAIN_NOT_REGISTER("HIS-1063"),
    MOBILE_TYPE_INVALID("HIS-1064"),

    
    INVALID_AADHAR_NUMBER("HIS-2001"),
    UNAUTHORIZED_ASA_MISSMATCH("HIS-2002"),
    UNSPECIFIED_MISSMATCH("HIS-2003"),
	OTP_STORE_MISSMATCH("HIS-2004"),
	BIOMETRIC_LOCK("HIS-2005"),
	UNSUPPORTED_OPTION("HIS-2006"),
	AADHAAR_SUSPENDED("HIS-2007"),
	AADHAAR_CANCELLED("HIS-2008"),
	AADHAAR_SUSPENDED_STATUS("HIS-2009"),
	UNKNOWN_ERROR("HIS-2010"),
	PI_BASIC("HIS-2011"),
	PI_ADDRESS("HIS-2012"),
	BIOMETRC_MISSMATCH("HIS-2013"),
	DUPLICATE_FINGER_MISSMATCH("HIS-2014"),
	DUPLICATE_IRISES_MISSMATCH("HIS-2015"),
	AADHAAR_NUMBER_INVALID("HIS-2016"),
	OTP_FLOOD_AADHAR("HIS-2017"),
	AADHAR_INCORRECT("HIS-2018"),
	AADHAAR_BIOTYPE_INVALID("HIS-2019"),
	
	FMR_FIR_IN_SAME_TXN("HIS-2020"),
	BIOMETRIC_LOCKED_BY_HOLDER("HIS-2021"),
	INVALID_OTP("HIS-2022"),
	TXN_VALUE_MISMATCH("HIS-2023"),
	INVALID_SKEY_ENCRYPTION("HIS-2024"),
	INVALID_CI_VALUE_IN_SKEY("HIS-2025"),
	INVALID_PID_ENCRYPTION("HIS-2026"),
	INVALID_HMAC("HIS-2027"),
	PUBLIC_DEVICES_NOT_ALLOWED("HIS-2028"),
	DEVICES_CERTIFICATE_EXPIRED("HIS-2029"),
	DP_MASTER_CERTIFICATE_EXPIRED("HIS-2030"),
	REQUEST_EXPIRED("HIS-2031"),
	REQUEST_TIME_IN_FUTURE("HIS-2032"),
	DUPLICATE_REQUEST("HIS-2033"),
	HMAC_VALIDATION_FAILED("HIS-2034"),
	AUA_LICENSE_EXPIRED("HIS-2035"),
	INVALID_INPUT("HIS-2036"),
	UNSUPPORTED_LANGUAGE("HIS-2037"),
	DIGITAL_SIGNATURE_FAILED("HIS-2038"),
	INVALID_DIGITAL_SIGN_KEY("HIS-2039"),
	PIN_RESET_REQUIRED("HIS-2040"),
	INVALID_FINGER_POSITION("HIS-2041"),
	FID_USE_NOT_ALLOWED("HIS-2042"),
	NAME_SPACE_NOT_ALLOWED("HIS-2043"),
	REGISTERED_DEVICE_NOT_ALLOWED("HIS-2044"),
	DATA_NOT_AVAILABLE("HIS-3001"),
	AUTHENTICATION_FAILURE("HIS-3002"),
	INVALID_VID_NUMBER("HIS-3003"),
    EXPIRED_VID_NUMBER("HIS-3004"),
    MOBILE_NUMBER_NOT_LINKED("HIS-3005"),
    DOCUMENT_VERIFICATION_FAILURE_EXCEPTION("HIS-3006"),
    HID_ALREADY_EXIST("HIS-3007"),
    
    DOCUMENT_MISMATCHED_EXCEPTION("HIS-4000"),
    ALREADY_VERIFIED_ENROLLMENT_NO_EXCEPTION("HIS-4001"),
    ;

	private final String code;

	ErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return this.code;
	}

}

