package in.gov.abdm.abha.enrollment.exception.aadhaar.model;

/**
 * enum to respond error codes and message to endpoints
 * errors related to UIDAI
 */
public enum UidiaErrorCode {

	K100("AADHAR_INCORRECT"),
	K200("DATA_NOT_AVAILABLE"),
	K514("AUTHENTICATION_FAILURE"),
	K515("INVALID_VID_NUMBER"),
	K516("AUTHENTICATION_FAILURE"),
	K517("EXPIRED_VID_NUMBER"),
	
	A100("PI_BASIC"),
	A111("MOBILE_NUMBER_NOT_LINKED"),
	A200("PI_ADDRESS"),
	A300("BIOMETRC_MISSMATCH"),
	A310("DUPLICATE_FINGER_MISSMATCH"),
	A311("DUPLICATE_IRISES_MISSMATCH"),

	A312("FMR_FIR_IN_SAME_TXN"),
	A330("BIOMETRIC_LOCKED_BY_HOLDER"),
	A400("INVALID_OTP"),
	A402("TXN_VALUE_MISMATCH"),
	A500("INVALID_SKEY_ENCRYPTION"),
	A501("INVALID_CI_VALUE_IN_SKEY"),
	A502("INVALID_PID_ENCRYPTION"),
	A503("INVALID_HMAC"),
	A554("PUBLIC_DEVICES_NOT_ALLOWED"),
	A559("DEVICES_CERTIFICATE_EXPIRED"),
	A560("DP_MASTER_CERTIFICATE_EXPIRED"),
	A561("REQUEST_EXPIRED"),
	A562("REQUEST_TIME_IN_FUTURE"),
	A563("DUPLICATE_REQUEST"),
	A564("HMAC_VALIDATION_FAILED"),
	A565("AUA_LICENSE_EXPIRED"),
	A567("INVALID_INPUT"),
	A568("UNSUPPORTED_LANGUAGE"),
	A569("DIGITAL_SIGNATURE_FAILED"),
	A570("INVALID_DIGITAL_SIGN_KEY"),
	A571("PIN_RESET_REQUIRED"),
	A572("INVALID_FINGER_POSITION"),
	A586("FID_USE_NOT_ALLOWED"),
	A587("NAME_SPACE_NOT_ALLOWED"),
	A588("REGISTERED_DEVICE_NOT_ALLOWED"),
	
	A940("UNAUTHORIZED_ASA_MISSMATCH"),
	A941("UNSPECIFIED_ASA_MISSMATCH"),
	A950("OTP_STORE_MISSMATCH"),
	A951("BIOMETRIC_LOCK"),
	A980("UNSUPPORTED_OPTION"),
	A952("OTP_FLOOD_AADHAR"),
	A953("OTP_FLOOD_AADHAR"),
	A995("AADHAAR_SUSPENDED"),
	A996("AADHAAR_CANCELLED"),
	A997("AADHAAR_SUSPENDED"),
	A998("INVALID_AADHAR_NUMBER"),
	A999("UNKNOWN_ERROR"),
	;

	private final String code;

	UidiaErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return this.code;
	}

}