abdm:
  abha.enrollment.db.service: abha-enrollment-db
  aadhaar.service: abha-aadhaar-app

server:
  port: 7102

rsa:
  algorithm: RSA
  transformation:
    algorithm: RSA/ECB/PKCS1Padding
  private:
    key: nha_rsa_private_key.pem
  public:
    key: nha_rsa_public_key.pem

