#aadhaar:
#  uri:
#    otp:
#      send: http://localhost:9292/api/v3/aadhaar/sendOtp
#      verify: http://localhost:9292/api/v3/aadhaar/verifyOtp
#
#
#entities:
#  uri:
#    transaction:
#      add: http://localhost:9188/api/v3/transaction
#      get:
#        id :
#        txnId: http://localhost:9188/api/v3/transaction/txnId/
#    accounts:
#      add: http://localhost:9188/api/v3/account