#server:
#  port: 7102
#spring:
#  application:
#    name: abha-enrollment-app
#  redis:
#    database: 0
#    host: redis1.nha2abdmdevpaas.tatacommunications.com
##    host: 100.96.1.9
#    port: 5105
#    password: nk8abFAL
#    timeout: 60000
#
#redis:
#  expireTimeInMinutes: 30
#
#enrollment:
#  domain: abdm
#  otp:
#    userBlockTimeInMinutes: 5
#    maxSendOtpCount: 3
#    maxVerifyOtpCount: 3
#  gateway:
#    aadhaar:
#      baseuri: http://global2dev.abdm.gov.internal
##      baseuri: http://localhost:9292
#    enrollmentdb:
#      baseuri: http://abha2dev.abdm.gov.internal
##      baseuri: http://localhost:9188
#    idp:
#      baseuri: http://global2dev.abdm.gov.internal
#    notification:
#      baseuri: http://global2dev.abdm.gov.internal
#    notificationdb:
#      baseuri: http://global2dev.abdm.gov.internal
#    lgd:
#      baseuri: http://global2dev.abdm.gov.internal
#    document:
#      baseuri: http://global2dev.abdm.gov.internal
#    documentdb:
#      baseuri: http://global2dev.abdm.gov.internal
#
#
#rsa:
#  algorithm: RSA
#  transformation:
#    algorithm: RSA/ECB/PKCS1Padding
#  private:
#    key: nha_rsa_private_key.pem
#  public:
#    key: nha_rsa_public_key.pem
#cipher:
#  secretKey: ENC(HmihGqsAn7SgZyvrp3awvMkYipmXXn4q+dgRtVPVNTc3yPNHGKlJpw==)