server:
  port: ${ENROLLMENT_APP_SERVICE_PORT}
spring:
  application:
    name: ${ENROLLMENT_APP_SERVICE_NAME}
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 60000

redis:
  expireTimeInMinutes: 30

enrollment:
  otp:
    userBlockTimeInMinutes: 5
    maxSendOtpCount: 3
    maxVerifyOtpCount: 3
  gateway:
    aadhaar:
      baseuri: ${AADHAAR_SERVICE_BASE_URI}
    enrollmentdb:
      baseuri: ${ENROLLMENT_DB_BASE_URI}
    idp:
      baseuri: ${IDP_SERVICE_BASE_URI}
    notification:
      baseuri: ${NOTIFICATION_SERVICE_BASE_URI}
    notificationdb:
      baseuri: ${NOTIFICATION_DB_BASE_URI}
    lgd:
      baseuri: ${LGD_SERVICE_BASE_URI}
    document:
      baseuri: ${DOCUMENT_SERVICE_BASE_URI}
    documentdb:
      baseuri: ${DOCUMENT_DB_BASE_URI}


rsa:
  algorithm: RSA
  transformation:
    algorithm: RSA/ECB/PKCS1Padding
  private:
    key: nha_rsa_private_key.pem
  public:
    key: nha_rsa_public_key.pem
