#spring:
#  r2dbc:
#    url: r2dbc:postgresql://100.96.1.9:5022/ndhm_dev
#    username: postgres
#    password: TAta12#$

spring:
  r2dbc:
    url: r2dbc:postgresql://100.65.137.200:5432/ndhm_beta
    username: ndhmbeta
    password: 1IdNdhm#Beta
