server:
  port: ${ENROLLMENT_DB_SERVICE_PORT}
spring:
  zipkin:
    baseUrl: ${ZIPKIN_BASE_URL}
    sender:
      type: web
    service:
      name: ${brave.localServiceName:${spring.application.name}}
    check-timeout: 10000
  sleuth:
    sampler:
      percentage: 1.0

  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL}
  application:
    name: ${ENROLLMENT_DB_SERVICE_NAME}

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: ${POOL_ENABLED}
      initial: ${POOL_INIT}
      max-size: ${POOL_MAX}
      maxIdleTime: ${POOL_TIMEOUT}
kafka:
  group:
    id: ${KAFKA_GROUP_ID}
  abha:
    patient:
      sync:
        topic: ${KAFKA_ABHA_PATIENT_SYNC_TOPIC}
        ack:
          topic: ${KAFKA_ABHA_PATIENT_SYNC_ACK_TOPIC}
    phr:
      sync:
        topic: ${KAFKA_ABHA_PHR_SYNC_TOPIC}
        ack:
          topic: ${KAFKA_ABHA_PHR_SYNC_ACK_TOPIC}
logging:
  pattern:
    level: "[%X{user_name}] [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"
