#server:
#  port: 9188
#spring:
#  application:
#    name: abha-enrollment-db
#
#  r2dbc:
#    url: r2dbc:postgresql://100.96.1.9:5022/abha?schema=abdm
#    username: abdmuser
#    password: welcome@123
