#server:
#  port: 7012
#spring:
#  zipkin:
#    baseUrl: https://webhook.site/553362c9-f161-482e-9949-4c31d497e4db
#    sender:
#      type: web
#    service:
#      name: ${brave.localServiceName:${spring.application.name}}
#  sleuth:
#    sampler:
#      percentage: 1.0
#
#  kafka:
#    bootstrap-servers: 100.96.1.9:5101
#  application:
#    name: app-enrollment-dbservice
#
#  r2dbc:
#    url: r2dbc:postgresql://100.96.1.9:5022/abha?schema=abdm
#    username: abdmuser
#    password: welcome@123
#kafka:
#  group:
#    id: sync-backend-db
#  abha:
#    patient:
#      sync:
#        topic: dev.abha.patient.sync
#        ack:
#          topic: dev.abha.patient.sync.ack
#    phr:
#      sync:
#        topic: dev.abha.phr.sync
#        ack:
#          topic: dev.abha.phr.sync.ack
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,refresh
#logging:
#  pattern:
#    level: "[%X{user_name}] [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"
